# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Manage_pb2 as Manage__pb2


class ContainerManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListContainers = channel.unary_unary(
                '/ContainerManager/ListContainers',
                request_serializer=Manage__pb2.ListContainers_Request.SerializeToString,
                response_deserializer=Manage__pb2.ListContainers_Response.FromString,
                )
        self.PruneContainers = channel.unary_unary(
                '/ContainerManager/PruneContainers',
                request_serializer=Manage__pb2.PruneContainers_Request.SerializeToString,
                response_deserializer=Manage__pb2.PruneContainers_Response.FromString,
                )
        self.GetContainer = channel.unary_unary(
                '/ContainerManager/GetContainer',
                request_serializer=Manage__pb2.GetContainer_Request.SerializeToString,
                response_deserializer=Manage__pb2.GetContainer_Response.FromString,
                )
        self.StartContainer = channel.unary_unary(
                '/ContainerManager/StartContainer',
                request_serializer=Manage__pb2.StartContainer_Request.SerializeToString,
                response_deserializer=Manage__pb2.StartContainer_Response.FromString,
                )
        self.StopContainer = channel.unary_unary(
                '/ContainerManager/StopContainer',
                request_serializer=Manage__pb2.StopContainer_Request.SerializeToString,
                response_deserializer=Manage__pb2.StopContainer_Response.FromString,
                )
        self.RestartContainer = channel.unary_unary(
                '/ContainerManager/RestartContainer',
                request_serializer=Manage__pb2.RestartContainer_Request.SerializeToString,
                response_deserializer=Manage__pb2.RestartContainer_Response.FromString,
                )
        self.RemoveContainer = channel.unary_unary(
                '/ContainerManager/RemoveContainer',
                request_serializer=Manage__pb2.RemoveContainer_Request.SerializeToString,
                response_deserializer=Manage__pb2.RemoveContainer_Response.FromString,
                )
        self.CreateContainer = channel.unary_unary(
                '/ContainerManager/CreateContainer',
                request_serializer=Manage__pb2.CreateContainer_Request.SerializeToString,
                response_deserializer=Manage__pb2.CreateContainer_Response.FromString,
                )
        self.GetFile = channel.unary_stream(
                '/ContainerManager/GetFile',
                request_serializer=Manage__pb2.GetFile_Request.SerializeToString,
                response_deserializer=Manage__pb2.GetFile_Response.FromString,
                )
        self.UpdateFile = channel.stream_unary(
                '/ContainerManager/UpdateFile',
                request_serializer=Manage__pb2.UpdateFile_Request.SerializeToString,
                response_deserializer=Manage__pb2.UpdateFile_Response.FromString,
                )
        self.ListFile = channel.unary_unary(
                '/ContainerManager/ListFile',
                request_serializer=Manage__pb2.ListFile_Request.SerializeToString,
                response_deserializer=Manage__pb2.ListFile_Response.FromString,
                )


class ContainerManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PruneContainers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContainers,
                    request_deserializer=Manage__pb2.ListContainers_Request.FromString,
                    response_serializer=Manage__pb2.ListContainers_Response.SerializeToString,
            ),
            'PruneContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.PruneContainers,
                    request_deserializer=Manage__pb2.PruneContainers_Request.FromString,
                    response_serializer=Manage__pb2.PruneContainers_Response.SerializeToString,
            ),
            'GetContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainer,
                    request_deserializer=Manage__pb2.GetContainer_Request.FromString,
                    response_serializer=Manage__pb2.GetContainer_Response.SerializeToString,
            ),
            'StartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartContainer,
                    request_deserializer=Manage__pb2.StartContainer_Request.FromString,
                    response_serializer=Manage__pb2.StartContainer_Response.SerializeToString,
            ),
            'StopContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopContainer,
                    request_deserializer=Manage__pb2.StopContainer_Request.FromString,
                    response_serializer=Manage__pb2.StopContainer_Response.SerializeToString,
            ),
            'RestartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartContainer,
                    request_deserializer=Manage__pb2.RestartContainer_Request.FromString,
                    response_serializer=Manage__pb2.RestartContainer_Response.SerializeToString,
            ),
            'RemoveContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContainer,
                    request_deserializer=Manage__pb2.RemoveContainer_Request.FromString,
                    response_serializer=Manage__pb2.RemoveContainer_Response.SerializeToString,
            ),
            'CreateContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContainer,
                    request_deserializer=Manage__pb2.CreateContainer_Request.FromString,
                    response_serializer=Manage__pb2.CreateContainer_Response.SerializeToString,
            ),
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=Manage__pb2.GetFile_Request.FromString,
                    response_serializer=Manage__pb2.GetFile_Response.SerializeToString,
            ),
            'UpdateFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateFile,
                    request_deserializer=Manage__pb2.UpdateFile_Request.FromString,
                    response_serializer=Manage__pb2.UpdateFile_Response.SerializeToString,
            ),
            'ListFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFile,
                    request_deserializer=Manage__pb2.ListFile_Request.FromString,
                    response_serializer=Manage__pb2.ListFile_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ContainerManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContainerManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/ListContainers',
            Manage__pb2.ListContainers_Request.SerializeToString,
            Manage__pb2.ListContainers_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PruneContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/PruneContainers',
            Manage__pb2.PruneContainers_Request.SerializeToString,
            Manage__pb2.PruneContainers_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/GetContainer',
            Manage__pb2.GetContainer_Request.SerializeToString,
            Manage__pb2.GetContainer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/StartContainer',
            Manage__pb2.StartContainer_Request.SerializeToString,
            Manage__pb2.StartContainer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/StopContainer',
            Manage__pb2.StopContainer_Request.SerializeToString,
            Manage__pb2.StopContainer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/RestartContainer',
            Manage__pb2.RestartContainer_Request.SerializeToString,
            Manage__pb2.RestartContainer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/RemoveContainer',
            Manage__pb2.RemoveContainer_Request.SerializeToString,
            Manage__pb2.RemoveContainer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/CreateContainer',
            Manage__pb2.CreateContainer_Request.SerializeToString,
            Manage__pb2.CreateContainer_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ContainerManager/GetFile',
            Manage__pb2.GetFile_Request.SerializeToString,
            Manage__pb2.GetFile_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ContainerManager/UpdateFile',
            Manage__pb2.UpdateFile_Request.SerializeToString,
            Manage__pb2.UpdateFile_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContainerManager/ListFile',
            Manage__pb2.ListFile_Request.SerializeToString,
            Manage__pb2.ListFile_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
